package com.agent.android.agent.device

enum class CapabilityClassification {
    NORMAL_APP_SUPPORTED,
    USER_PERMISSION_REQUIRED,
    SPECIAL_ACCESS_REQUIRED,
    ACCESSIBILITY_REQUIRED,
    DEVICE_OWNER_REQUIRED,
    PROFILE_OWNER_REQUIRED,
    SYSTEM_PRIVILEGED_REQUIRED,
    HARDWARE_UNAVAILABLE,
    OS_RESTRICTED,
    OEM_RESTRICTED,
    NOT_SUPPORTED,
    UNKNOWN
}
